# Generated by Django 5.0.1 on 2024-02-12 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('customization_id', models.AutoField(primary_key=True, serialize=False)),
                ('customization_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Customization',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('seller_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SellerProduct',
            },
        ),
        migrations.CreateModel(
            name='SellerProductCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_customization', models.BooleanField(default=True)),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.customization')),
                ('seller_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sellerproduct')),
            ],
            options={
                'db_table': 'SellerProductCustomization',
            },
        ),
    ]
