# Generated by Django 5.0.1 on 2024-01-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sellerprofile',
            table='seller_profile',
        ),
    ]
