# Generated by Django 5.0.1 on 2024-01-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_sellerprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
